
# 请求单页数据的数量
PAGE_SIZE = 100

# 每次请求的间隔时间
WAIT_TIME = 1

# 异常类型 fs：负损，gs：高损，bks：不可算
ABNORMAL_TYPE = ['fs', 'gs', 'bks']

# process 中阈值
THRESHOLD = {
    'EC': 0.33,
    'EV': 0.1,
    'DAY': 8,
    'FACTOR': 80,
}

ORG_ID = (
    '1C3DAEFA42964361BCF73D24F19127F9',  # 国网山西省电力公司太原供电公司
    'D3305320A16D4D1EB4A82DD6A7C75A47',  # 国网山西省电力公司太原供电公司客户服务中心
    '2149E6A13F914916B3B0A302D9ECEE47',  # 国网山西省电力公司阳曲县供电公司
    'CAC0177E0D5C4888BFE954807FC950C3',  # 国网山西省电力公司太原市滨河供电公司
    '1EE838F9DE26498A98FD52AF06A38442',  # 国网山西省电力公司太原市小店区供电公司
    '605B8D251DCD48319A16CEC57F7CCB59',  # 国网山西省电力公司古交市供电公司
    '6486B6061D7E41A9907A3D177ABBB9CC',  # 国网山西省电力公司清徐县供电公司
    '90897704C6814E10B508A3E4CE61F6E3',  # 国网山西省电力公司娄烦县供电公司
    'B578186E441744B0AC87BB6116BA2E53',  # 国网山西省电力公司太原市晋源区供电公司
)

ORG_ID_DICT = {
    ORG_ID[0]: '国网山西省电力公司太原供电公司',
    ORG_ID[1]: '国网山西省电力公司太原供电公司客户服务中心',
    ORG_ID[2]: '国网山西省电力公司阳曲县供电公司',
    ORG_ID[3]: '国网山西省电力公司太原市滨河供电公司',
    ORG_ID[4]: '国网山西省电力公司太原市小店区供电公司',
    ORG_ID[5]: '国网山西省电力公司古交市供电公司',
    ORG_ID[6]: '国网山西省电力公司清徐县供电公司',
    ORG_ID[7]: '国网山西省电力公司娄烦县供电公司',
    ORG_ID[8]: '国网山西省电力公司太原市晋源区供电公司',
}

SQL = {
    'host': '172.16.3.162',
    'port': 3306,
    'user': 'root',
    'passwd': '123456',
    'db': 'beiyiqu_data',
    'charset': 'utf8'
}

LOGIN_DATA = {
    'wangsheng': 'sx',
    'username': 'suxn2627',
    'password':
    '456971c3d25109fc60bf97d17554fc56e793bbd4df795a1bf3bd728b92c67f43c63ec4cb90fe6aca4b56fe19555688739788dd8d8cd36f27290010b0b8beeda1836fba2c33d34f1b7dfe13ee026b9fb38494041f12ef3d4fdcd36ec1f5f28846bd1119351855f9df9a3b978cd4e67bbb8f411eaa6f200feedc396484ee1e1bb4',
    'lt': 'LT-2358068-zoyStAGX29lacMLzQnHsHVLawClNrZ',
    'execution': 'e1s1',
    '_eventId': 'submit',
    'm':
    '00a9065378eddc455c15143b4a733fdcb3ef29c4e7598522c5fcfff580d5d98dbbcb3e132beae4fb5d5b5db6342cb4f455e84c9f9488663fd59c3676c99ea8c32463a0a0b75688ad364e9e12dbc4cec2fb331ee58bc3881c9869babd1b10677e39d5cb7c30f23be7547b2e6d8ed2cae8942e2767efc7ec804286e01484533ab47f',
    'e': '010001'
}

SIGN = {
    'TGAI': '不达标台区信息',
    'LAI': '不达标线路信息',
    'LPI': '线路电量线损信息',
    'TGPI': '台区电量线损信息',
    'GPI': '关口电量信息',
    'TGTV': '台区表底码值',
    'RC': '分区域完成情况',
    'VC': '分压完成情况',
    'LC': '线路完成情况',
    'LLC': '线路线损完成情况',
    'TGC': '台区完成情况',
    'TGLC': '台区线损完成情况',
    'IRC': '高压表底完整率完成情况',
    'TGEC': '台区电流值',
    'TGEV': '台区电压值',
    'TGPC': '台区功率曲线值',
    'TGPF': '台区功率因数值',
    'UTV': '用户表底码值',
}

URL = {
    'login': 'http://iscsso.sgcc.com.cn/isc_sso/login?service=http%3A%2F%2F10.4.39.180%2Fxsgl%2FmainFrame%2Fmain%2Findex.jsp',
    'TGAI': 'http://10.4.39.180/xsgl/assessAndEvaluationNew/rest/tgDailyNeg/queryDeial',
    'LAI': 'http://10.4.39.180/xsgl/assessAndEvaluationNew/rest/pdLineGfs/abnormal',
    'LPI': 'http://10.4.39.180/xsgl/spLoss/rest/hbaseSpLossLine/getSearch',
    'TGPI': 'http://10.4.39.180/xsgl/monitAndAnz/rest/hBaseController/searchTg',
    'GPI': 'http://10.4.39.180/xsgl/markManage/rest/lineMarkList/queryLineMarkTree',
    'TGTV': 'http://10.4.39.180/xsgl/monitAndAnz/rest/hBaseLBoardController/findSalePower',
    'RC1': 'http://10.4.39.180/xsgl/spLoss/rest/lossPowerRegion/querySpLossCityTree',  # 分区线损率
    'RC2': 'http://10.4.39.180/xsgl/examManage/rest/throryReportNew/query',            # 分区线损率基值
    'VC1': 'http://10.4.39.180/xsgl/spLoss/rest/lossPowerVolt/querySum',   # 220，110，35，10分压线损率
    'VC2': 'http://10.4.39.180/xsgl/spLoss/rest/fourVolt/queryDataDay',    # 380（400）分压线损率
    'VC3': 'http://10.4.39.180/xsgl/examManage/rest/throryReport/query',    # 220，110，35基值
    'VC4': 'http://10.4.39.180/xsgl/assessAndEvaluationNew/rest/inspectionLine/query', # 10基值
    'VC5': 'http://10.4.39.180/xsgl/assessAndEvaluationNew/rest/tqIndexSystemNew/query',    # 380基值
    'LC': 'http://10.4.39.180/xsgl/monitAndAnz/rest/linerun/lineinfo',
    'LLC': 'http://10.4.39.180/xsgl/assessAndEvaluationNew/rest/pdLineGfs/query',
    'TGC': 'http://10.4.39.180/xsgl/monitAndAnz/rest/tgrun/tginfo',
    'TGLC': 'http://10.4.39.180/xsgl/assessAndEvaluationNew/rest/tgDailyNeg/query',
    'TGEC': 'http://10.4.39.180/xsgl/monitAndAnz/rest/tgboard/sxdlphChartTb',
    'IRC': 'http://10.4.39.180/xsgl/examPlan/rest/staticPowerDay/query',
    'TGEV': 'http://10.4.39.180/xsgl/monitAndAnz/rest/tgboard/dyChartTb',
    'TGPC': 'http://10.4.39.180/xsgl/monitAndAnz/rest/tgboard/glqxChartTb',
    'TGPF': 'http://10.4.39.180/xsgl/monitAndAnz/rest/tgboard/glysChartTb',
    'UTV': 'http://10.4.39.180/xsgl/monitAndAnz/rest/tgboard/saledetail',
}

PARAMS = {
    'TGAI': '{"columns":"ORG_ID,ORG_NAME,STAT_DATE,TG_NO,TG_NAME,TRAN_NO,TRAN_NAME,NOT_STAND_DAYS,DATE_RANGE,__temp_Column_rnd__","filter":"dateTime=%s&orgId=1C3DAEFA42964361BCF73D24F19127F9&type=%s","pageIndex":%s,"pageSize":%s}',
    'LAI': '{"columns":"ORG_ID,ORG_NAME,STAT_DATE,LINE_NO,LINE_NAME,RATE_LOSS,NOT_STAND_DAYS,DATE_RANGE,__temp_Column_rnd__","filter":"type=%s&bdbType=undefined&statDate=%s&orgId=1C3DAEFA42964361BCF73D24F19127F9","pageIndex":%s,"pageSize":%s}',
    'LPI': '{"columns":"lineNo,lineId,lineType,mLineId,flag,orgId,uniqueId,objId,lineName,subsName,statDate,rateLossAnu,voltLevel,powerSup,powerOut,powerSal,powerLoss,rateLoss,lineGateNum,lmCopNum,lmSucRate,pubNumDist,pmCopNum,pmSucRate,priNumDist,primCopNum,primSucRate,lineTypeValue,responOrgName,responPer,tel,isUnloss,orgName,expType,anmid,__temp_Column_rnd__","filter":"dataCycle=0&level=1&orgId=1C3DAEFA42964361BCF73D24F19127F9&dateType=d&mergeLineIdIsNull=true&area=00&statDate=%s","pageIndex":%s,"pageSize":%s}',
    'TGPI': '{"columns":"orgName,lineNo,lineName,tgNo,tgName,powerSup,powerOut,powerSal,powerLoss,rateLoss","filter":"orgId=1C3DAEFA42964361BCF73D24F19127F9&lineId=%s&statDate=%s&dateType=0"}',
    'GPI': '{"columns":"lineNo,lineId,expType,modelId,objId,lineType,isCalsyndl,isCalsynml,adResonType,lineName,subsName,inOut,mpId,mpNo,mpName,meterId,dataSource,madeNo,assetNo,mpRate,calcRel,relAddMinusPap,relAddMinusRap,dataDate,zxSbd,zxXbd,zxPower,fxSbd,fxXbd,fxPower,zbdl,fxzbdl,switchNo,switchId,switchName,lineTypeValue,isCalsyndlValue,isCalsynmlValue,orgName,effectiveDate,responPer,tel,isCombine,mp,cp,loadMpId,text,__temp_Column_rnd__","filter":"searchFw=0&orgId=%s&rq=%s&timeType=0&accountDateType=tq&inOut=01&isZb=null&isMeterAdd=null&codeValue=null&isReport=null&isCombine=null","pageIndex":%s,"pageSize":%s}',
    'TGTV': '{"columns":"consTgName,consTgNo,meterId,madeNo,assetNo,consType,tFactor,relAddMinusPap,mpZxPower,zxsbd,zxxbd,relAddMinusRap,mpFxPower,fxsbd,fxxbd","filter":"orgId=1C3DAEFA42964361BCF73D24F19127F9&lineId=%s&statDate=%s&dateType=0&lineType=%s&mLineId=null"}', 
    'RC1': '{"columns":"ORG_NAME,ORG_ID,STAT_DATE,FLAG,NLJXSL,XSL,POWER_LOSS,POWER_SAL,POWER_TG,POWER_CONS,POWER_SUP,DCSW,SJGR,QTSR,QTSC,FBSDY,__temp_Column_rnd__","filter":"startDate=%s&endDate=%s&gflag=true&orgId=%s&orgType=%s&dayOrMonth=0&con=true","pageIndex":1,"pageSize":100}',
    'RC2': '{"columns":"OBJ_ID,ORG_ID,ORG_NAME,RATE_LOSS,STAND_PERCE,__temp_Column_rnd__","filter":"&orgId=%s","pageIndex":1,"pageSize":100}',
    'VC1': '{"columns":"objId,ve,voltLevel,orgId,orgName,sdate,rateLoss,powerLoss,powerSal,powerSup,powerInTotal,powerInOo,powerInOv,powerOutTotal,powerOutOo,powerOutOv,powerPp,powerDist,rateLossAnu,__temp_Column_rnd__","filter":"endMonth=%s&startMonth=%s&orgId=%s&dataCycle=0&lossType=1","pageIndex":1,"pageSize":100}',
    'VC2': '{"columns":"OBJ_ID,ORG_ID,ORG_NAME,STAT_DATE,RATE_LOSS,SUB_POWER,IN_POWER,TG_IN_POWER,DIST_POWER,OUT_POWER,TG_OUT_POWER,SAL_POWER,LOSS_POWER,H_CHILD,P_ORG_ID,ORG_LEVEL,SG_CODE,__temp_Column_rnd__","filter":"date=%s&orgId=%s&orgLevel=04&selectSelf=0&type=null&orgLevel1=04&root_orgId=","pageIndex":1,"pageSize":100}',
    'VC3': '{"columns":"OBJ_ID,ORG_ID,ORG_NAME,VOLT_LEVEL,QUARTER,RATE_LOSS,STAND_PERCE,__temp_Column_rnd__","filter":"&voltLevel=%s&orgId=%s","pageIndex":1,"pageSize":100}',
    'VC4': '{"columns":"ORG_ID,ORG_NAME,TQ_LOSS,BASE_RATE,SUBSTR_RATE,STAND_OR_NOT,GRADE_FY,ARCH_NUM,THIS_MONTH_RUN_NUM,MONTH_STAND_NUM,MONTH_UN_STAND_NUM,INCLUDE_NUM,MONTH_BASE_NUM,MONTH_RATE,DAY_STAND_NUM,DAY_UN_STAND_NUM,INCLUDE_DAY_NUM,DAY_BASE_NUM,DAY_RATE,STAND_RATE,GRADE,TOTAL_GRADE,__temp_Column_rnd__","filter":"&dateMon=%s&orgId=1C3DAEFA42964361BCF73D24F19127F9&selOrgLevel=04&type=F"}',
    'VC5': '{"columns":"ORG_ID,ORG_LEVEL,ORG_NAME,TQ_LOSS,BASE_RATE,SUBSTR_RATE,STAND_OR_NOT,GRADE_FY,ARCH_NUM,THIS_MONTH_RUN_NUM,MONTH_STAND_NUM,MONTH_UN_STAND_NUM,INCLUDE_NUM,MONTH_BASE_NUM,MONTH_RATE,DAY_STAND_NUM,DAY_UN_STAND_NUM,INCLUDE_DAY_NUM,DAY_BASE_NUM,DAY_RATE,STAND_RATE,GRADE,TOTAL_GRADE,__temp_Column_rnd__","filter":"&dateMon=%s&orgId=1C3DAEFA42964361BCF73D24F19127F9&selOrgLevel=04&type=S"}',
    'LC': '{"columns":"id,serialNumber,name,archNum,packNum,radiNum,unconNum,lineSumNum,lineNegNum,lineGsNum,lineHugeNum,lineUncalNum,lineSucNum,includeNum,lineSucRate,__temp_Column_rnd__","filter":"orgId=1C3DAEFA42964361BCF73D24F19127F9&dateCycle=0&statDate=%s&orgLevel=04"}',
    'LLC': '{"columns":"ORG_ID,ORG_NAME,STAT_DATE,ARCH_NUM,LAST_GEN_NUM,GEN_GOVERN_NUM,GEN_NEW_NUM,THIS_GEN_NUM,THIS_GEN_RATE,THIS_HIGH_NUM,THIS_HIGH_RATE,NOT_CALC_NUM,NOT_CALC_RATE,DAY1_NUM,DAY1_GEN_NUM,DAY1_HIGH_NUM,DAY1_N_CALC_NUM,DAY2_NUM,DAY2_GEN_NUM,DAY2_HIGH_NUM,DAY2_N_CALC_NUM,DAY3_NUM,DAY3_GEN_NUM,DAY3_HIGH_NUM,DAY3_N_CALC_NUM,DAY4_NUM,DAY4_GEN_NUM,DAY4_HIGH_NUM,DAY4_N_CALC_NUM,DAY5_NUM,DAY5_GEN_NUM,DAY5_HIGH_NUM,DAY5_N_CALC_NUM,DAY6_NUM,DAY6_GEN_NUM,DAY6_HIGH_NUM,DAY6_N_CALC_NUM,DAYN_NUM,DAYN_GEN_NUM,DAYN_HIGH_NUM,DAYN_N_CALC_NUM,__temp_Column_rnd__","filter":"statDate=%s&orgId=1C3DAEFA42964361BCF73D24F19127F9"}',
    'TGC': '{"columns":"id,serialNumber,name,porgId,archNum,packNum,radiNum,unconNum,tgSumNum,tgNegNum,tgGsNum,tgHugeNum,tgUncalNum,tgSucNum,includeNum,tgSucRate,__temp_Column_rnd__","filter":"orgId=%s&dateCycle=0&statDate=%s&orgLevel=%s"}',
    'TGLC': '{"columns":"ORG_ID,ORG_NAME,STAT_DATE,ARCH_NUM,LAST_GEN_NUM,GEN_GOVERN_NUM,GEN_NEW_NUM,THIS_GEN_NUM,THIS_GEN_RATE,THIS_HIGH_NUM,THIS_HIGH_RATE,NOT_CALC_NUM,NOT_CALC_RATE,DAY1_NUM,DAY1_GEN_NUM,DAY1_HIGH_NUM,DAY1_N_CALC_NUM,DAY2_NUM,DAY2_GEN_NUM,DAY2_HIGH_NUM,DAY2_N_CALC_NUM,DAY3_NUM,DAY3_GEN_NUM,DAY3_HIGH_NUM,DAY3_N_CALC_NUM,DAY4_NUM,DAY4_GEN_NUM,DAY4_HIGH_NUM,DAY4_N_CALC_NUM,DAY5_NUM,DAY5_GEN_NUM,DAY5_HIGH_NUM,DAY5_N_CALC_NUM,DAY6_NUM,DAY6_GEN_NUM,DAY6_HIGH_NUM,DAY6_N_CALC_NUM,DAYN_NUM,DAYN_GEN_NUM,DAYN_HIGH_NUM,DAYN_N_CALC_NUM,__temp_Column_rnd__","filter":"dateTime=%s&orgId=%s"}',
    'IRC': '{"columns":"ORG_ID,ORG_LEVEL,ORG_NAME,MARK_NUM,MARK_ERR_NUM,MARK_ERR_RATE,MARK_FULL_NUM,MARK_UN_FULL_NUM,MARK_FULL_RATE,METER_LOG_ERR_NUM,METER_LOG_ERR_RATE,CONS_NUM,CONS_FULL_NUM,CONS_UN_FULL_NUM,CONS_FULL_RATE,TRAN_FULL_NUM,TRAN_UN_FULL_NUM,TRAN_FULL_RATE,TRAN_NUM,__temp_Column_rnd__","filter":"&dateMon=%s&orgId=1C3DAEFA42964361BCF73D24F19127F9&selOrgLevel=04"}',
    'UTV': '{"columns":"consName,mpNo,mpName,meterId,madeNo,assertNo,tfactory,lastMrNum,thisRead,thisReadPq,lastReadPq,prtPq,lastPeriod,wiringMode,tgName,consNo,elecAddr","filter":"orgId=1C3DAEFA42964361BCF73D24F19127F9&tgId=%s&statDate=%s&dateType=0&isPCalChildren=null","pageIndex":%s,"pageSize":%s}',
}

TABLE_NAME = {
    'TGAI': 'tg_abnormal_info',
    'LAI': 'line_abnormal_info',
    'LPI': 'line_power_info',
    'TGPI': 'tg_power_info',
    'GPI': 'gateway_power_info',
    'TGTV': 'tg_table_value',
    'RC': 'region_completion',
    'VC': 'voltage_completion',
    'LC': 'line_completion',
    'LLC': 'line_loss_completion',
    'TGC': 'tg_completion',
    'TGLC': 'tg_loss_completion',
    'IRC': 'integrity_rate_completion',
    'TGEC': 'tg_electric_current',
    'TGEV': 'tg_electric_voltage',
    'TGPC': 'tg_power_curve',
    'TGPF': 'tg_power_factor',
    'UTV': 'user_table_value',
}

TABLE = {
    'TGAI': (
        "TG_NAME",
        "TRAN_ID",
        "TG_ID",
        "NOT_STAND_DAYS",
        "ORG_NAME",
        "ROWNUM_",
        "TRAN_NO",
        "TRAN_NAME",
        "statDate",
        "TG_NO",
        "ABNORMAL_TYPE",
        "DATE_RANGE"
    ),
    'LAI': (
        "MODEL_ORG_ID",
        "NOT_STAND_DAYS",
        "ORG_NAME",
        "LINE_TYPE",
        "RATE_LOSS",
        "statDate",
        "MERGE_LINE_ID",
        "DATE_RANGE",
        "LINE_ID",
        "ORG_ID",
        "LINE_NAME",
        "LINE_NO",
        "ABNORMAL_TYPE"
    ),
    'LPI': (
        "isUnloss",
        "tel",
        "powerBiguser",
        "orgId",
        "rateLoss",
        "lmSucRate",
        "lineName",
        "lvConsNum",
        "modifyTime",
        "subsId",
        "zxlName",
        "vmSucRate",
        "nLossPower",
        "pmCopNum",
        "lineNo",
        "isCalsyndl",
        "statDate",
        "lineGateNum",
        "isCalsynml",
        "voltLevel",
        "isEffective",
        "threeUnbal",
        "responOrgName",
        "nLossRateLoss",
        "exptype",
        "createTime",
        "rowkey",
        "tgMpNum",
        "hashRowKey",
        "anmid",
        "responPer",
        "vmCopNum",
        "responOrg",
        "sortNo",
        "lineType",
        "objId",
        "powerSal",
        "effectiveDate",
        "subsName",
        "pmSucRate",
        "lineId",
        "primSucRate",
        "pubNumDist",
        "mergeLineId",
        "mainLineId",
        "expiryDate",
        "powerOut",
        "powerLoss",
        "lmCopNum",
        "priNumDist",
        "orgName",
        "pmSucEate",
        "primCopNum",
        "calcHourLoss",
        "powerTg",
        "isCombine",
        "powerSup",
        "nLossPowerLoss",
        "sgCode"
    ),
    'TGPI': (
        "isUnloss",
        "rowkey",
        "tgMpNum",
        "vmCopNum",
        "tgName",
        "powerBiguser",
        "orgId",
        "rateLoss",
        "lmSucRate",
        "lineName",
        "powerSal",
        "objId",
        "tgId",
        "lvConsNum",
        "pmSucRate",
        "vmSucRate",
        "primSucRate",
        "pubNumDist",
        "nLossPower",
        "pmCopNum",
        "lineNo",
        "powerOut",
        "powerLoss",
        "lmCopNum",
        "priNumDist",
        "orgName",
        "accStartDate",
        "pmSucEate",
        "primCopNum",
        "statDate",
        "lineGateNum",
        "powerTg",
        "accNotNum",
        "accNum",
        "tgNo",
        "powerSup",
        "threeUnbal",
        "nLossRateLoss",
        "ccNum",
        "nLossPowerLoss",
        "lineId"
    ),
    'GPI': (
        "monitorId",
        "fxPower",
        "relAddMinusPap",
        "relAddMinusRap",
        "orgId",
        "calcRel", 
        "lineName",
        "mpNo",
        "subsId",
        "fxSbd",
        "lineNo",
        "modelId",
        "zxPower",
        "dataSource",
        "zxSbd",
        "mpId",
        "lineType",
        "outIn",
        "objId",
        "effectiveDate",
        "subsName",
        "mpEffectDate",
        "lineId",
        "fxXbd",
        "mpRate",
        "mpName",
        "orgName",
        "zxXbd",
        "statDate",
    ),
    'TGTV': (
        "mpLastZxPower",
        "tFactor",
        "relAddMinusPap",
        "consTgName",
        "mpId",
        "lineType",
        "orgId",
        "madeNo",
        "zxsbd",
        "lineName",
        "mpNo",
        "fxsbd",
        "mpZxPower",
        "lineId",
        "consTgId",
        "assetNo",
        "zxxbd",
        "lineNo",
        "consType",
        "mpName",
        "dateType",
        "statDate",
        "meterId",
        "mpFxPower",
        "mpLastFxPower",
        "success",
        "fxxbd",
        "consTgNo",
        "sgCode",
        'PBLineId',
        'PBLineNo',
        'PBLineName',
        'PBLineType'
    ),
    'UTV': (
        "serialNumber",
        "consId",
        "consNo",
        "consName",
        "tgName",
        "mpId",
        "meterId",
        "wiringMode",
        "tfactory",
        "lastMrNum",
        "thisRead",
        "thisReadPq",
        "lastReadPq",
        "prtPq",
        "lastPeriod",
        "madeNo",
        "assertNo",
        "mpNo",
        "mpName",
        "elecAddr",
        "tgId",
        "statDate"
    ),
    'TGEC': (
        "consTgId",
        "statDate",
        "threePhase",
        "h0",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "h7",
        "h8",
        "h9",
        "h10",
        "h11",
        "h12",
        "h13",
        "h14",
        "h15",
        "h16",
        "h17",
        "h18",
        "h19",
        "h20",
        "h21",
        "h22",
        "h23",
    ),
    'TGEV': (
        "consTgId",
        "statDate",
        "threePhase",
        "h0",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "h7",
        "h8",
        "h9",
        "h10",
        "h11",
        "h12",
        "h13",
        "h14",
        "h15",
        "h16",
        "h17",
        "h18",
        "h19",
        "h20",
        "h21",
        "h22",
        "h23",
    ),
    'TGPC': (
        "consTgId",
        "statDate",
        "h0",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "h7",
        "h8",
        "h9",
        "h10",
        "h11",
        "h12",
        "h13",
        "h14",
        "h15",
        "h16",
        "h17",
        "h18",
        "h19",
        "h20",
        "h21",
        "h22",
        "h23",
    ),
    'TGPF': (
        "consTgId",
        "statDate",
        "h0",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "h7",
        "h8",
        "h9",
        "h10",
        "h11",
        "h12",
        "h13",
        "h14",
        "h15",
        "h16",
        "h17",
        "h18",
        "h19",
        "h20",
        "h21",
        "h22",
        "h23",
    ),
    'LC': (
        "includeNum",
        "unSucTotal",
        "hasChildren",
        "totalCopRate",
        "packNum",
        "lineSumNum",
        "lineHugeNum",
        "serialNumber",
        "lineNegNum",
        "statDate",
        "archNum",
        "radiNum",
        "lineCalNum",
        "orgId",
        "lineUncalNum",
        "unconNum",
        "lineSucNum",
        "lineSucRate",
        "dateCycle",
        "orgName",
        "lineGsNum",
        "porgId",
        "sgCode",
        "orgLevel"
    ),
    'LLC': (
        "DAY5_NUM",
        "SORT_NO",
        "DAY4_N_CALC_NUM",
        "DAYN_GEN_NUM",
        "DAY3_N_CALC_NUM",
        "H_CHILD",
        "DAY6_GEN_NUM",
        "DAY1_HIGH_NUM",
        "ORG_NAME",
        "DAY4_HIGH_NUM",
        "ORG_LEVEL",
        "DAY6_HIGH_NUM",
        "DAY2_NUM",
        "DAY6_NUM",
        "DAYN_NUM",
        "DAY2_HIGH_NUM",
        "P_ORG_ID",
        "NOT_CALC_NUM",
        "DAY3_HIGH_NUM",
        "ARCH_NUM",
        "DAY4_NUM",
        "DAY1_N_CALC_NUM",
        "DAY3_NUM",
        "DAY2_GEN_NUM",
        "DAY5_HIGH_NUM",
        "DAY1_GEN_NUM",
        "NOT_CALC_RATE",
        "DAY1_NUM",
        "THIS_GEN_RATE",
        "ORG_NAME1",
        "DAY2_N_CALC_NUM",
        "THIS_HIGH_NUM",
        "DAY5_GEN_NUM",
        "THIS_HIGH_RATE",
        "statDate",
        "ORG_ID",
        "DAY6_N_CALC_NUM",
        "DAY4_GEN_NUM",
        "DAY3_GEN_NUM",
        "THIS_GEN_NUM",
        "LAST_GEN_NUM",
        "DAYN_N_CALC_NUM",
        "DAYN_HIGH_NUM",
        "DAY5_N_CALC_NUM",
        "GEN_NEW_NUM",
        "GEN_GOVERN_NUM" 
    ),
    'TGC': (
        "includeNum",
        "hasChildren",
        "tgCalNum",
        "packNum",
        "tgHugeNum",
        "tgUncalNum",
        "tgSucNum",
        "serialNumber",
        "tgGsNum",
        "tgSumNum",
        "statDate",
        "archNum",
        "tgSucRate",
        "radiNum",
        "orgId",
        "unconNum",
        "dateCycle",
        "orgName",
        "porgId",
        "tgNegNum",
        "sgCode",
        "orgLevel"
    ),
    'TGLC': (
        "DAY5_NUM",
        "SORT_NO",
        "DAY4_N_CALC_NUM",
        "DAYN_GEN_NUM",
        "DAY3_N_CALC_NUM",
        "H_CHILD",
        "DAY6_GEN_NUM",
        "DAY1_HIGH_NUM",
        "ORG_NAME",
        "DAY4_HIGH_NUM",
        "ORG_LEVEL",
        "DAY6_HIGH_NUM",
        "DAY2_NUM",
        "DAY6_NUM",
        "DAYN_NUM",
        "DAY2_HIGH_NUM",
        "P_ORG_ID",
        "NOT_CALC_NUM",
        "DAY3_HIGH_NUM",
        "ARCH_NUM",
        "DAY4_NUM",
        "DAY1_N_CALC_NUM",
        "DAY3_NUM",
        "DAY2_GEN_NUM",
        "DAY5_HIGH_NUM",
        "DAY1_GEN_NUM",
        "NOT_CALC_RATE",
        "DAY1_NUM",
        "THIS_GEN_RATE",
        "ORG_NAME1",
        "DAY2_N_CALC_NUM",
        "THIS_HIGH_NUM",
        "DAY5_GEN_NUM",
        "THIS_HIGH_RATE",
        "statDate",
        "ORG_ID",
        "DAY6_N_CALC_NUM",
        "DAY4_GEN_NUM",
        "DAY3_GEN_NUM",
        "THIS_GEN_NUM",
        "LAST_GEN_NUM",
        "DAYN_N_CALC_NUM",
        "DAYN_HIGH_NUM",
        "DAY5_N_CALC_NUM",
        "GEN_NEW_NUM",
        "GEN_GOVERN_NUM"   
    ),
    'IRC': (
        "SORT_NO",
        "MARK_ERR_RATE",
        "H_CHILD",
        "ORG_NAME",
        "CONS_FULL_RATE",
        "DAY_NUM",
        "SGNAME",
        "TRAN_UN_FULL_NUM",
        "ORG_LEVEL",
        "TRAN_FULL_NUM",
        "MARK_FULL_NUM",
        "TRAN_FULL_RATE",
        "TRAN_NUM",
        "MARK_FULL_RATE",
        "MARK_NUM",
        "ORG_ID",
        "MARK_ERR_NUM",
        "MARK_UN_FULL_NUM",
        "P_ORG_ID",
        "CONS_FULL_NUM",
        "CONS_NUM",
        "statDate",
        "CONS_UN_FULL_NUM"
    ),
    'RC': (
        "SJGR",
        "WS",
        "OBJ_ID",
        "XSLJIA",
        "ORG_NAME",
        "QTSC",
        "POWER_LOSSJIA",
        "POWER_LOSS",
        "XSL",
        "FBSDY",
        "ORG_LEVEL",
        "POWER_TG",
        "statDate",
        "DCSW",
        "POWER_SAL",
        "ORG_ID",
        "QTSR",
        "POWER_SUPJIA",
        "POWER_SUP",
        "NLJXSL",
        "POWER_CONS",
        "POWER_SALJIA",
        'RATE_LOSS',
        'STAND_PERCE',
    ),
    'VC': (
        "orgId",
        "orgName",
        "rateLoss",
        "powerLoss",
        "powerSal",
        "powerSup",
        "powerIn",
        "powerOut",
        "voltLevel",
        "ve",
        'baseRate',
        'standPerce',
        "statDate",
    ),
}

HEADER = {
    'iscsso': {
        'Host': 'iscsso.sgcc.com.cn',
        'Content-Length': '642',
        'Cache-Control': 'max-age=0',
        'Origin': 'http://iscsso.sgcc.com.cn',
        'Upgrade-Insecure-Requests': '1',
        'Content-Type': 'application/x-www-form-urlencoded',
        'User-Agent':
        'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36',
        'Accept':
        'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
        'Referer':
        'http://iscsso.sgcc.com.cn/isc_sso/login?service=http%3A%2F%2F10.4.39.180%3A80%2Fxsgl%2FmainFrame%2Fmain%2Findex.jsp',
        'Accept-Encoding': 'gzip, deflate',
        'Accept-Language': 'zh-CN,zh;q=0.9'
    },
    '10.4.39.180': {
        'Host': '10.4.39.180',
        'Cache-Control': 'max-age=0',
        'Upgrade-Insecure-Requests': '1',
        'User-Agent':
        'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36',
        'Accept':
        'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
        'Referer':
        'http://iscsso.sgcc.com.cn/isc_sso/login?service=http%3A%2F%2F10.4.39.180%3A80%2Fxsgl%2FmainFrame%2Fmain%2Findex.jsp',
        'Accept-Encoding': 'gzip, deflate',
        'Accept-Language': 'zh-CN,zh;q=0.9',
        'Connection': 'keep-alive'
    }
}